[env]
RUST_TARGET_PATH = "${PWD}"

[tasks.bootstrap]
description = "Runs the rust compiler."
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--bin=bootstrap"]

[tasks.bootstrap-release]
description = "Runs the rust compiler."
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--bin=bootstrap", "--release"]

[tasks.bootstrap-iso]
description = "Creates a bootable ISO containing the bootstrap and grub."
dependencies = ["bootstrap"]
script = [
'''
cp target/i386-unknown-none/debug/bootstrap ../isofiles/boot/bootstrap.bin
'''
]

[tasks.doc]
description = "Document the bootstrap"
dependencies = ["bootstrap"]
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot"}
command = "cargo"
args = ["rustdoc", "--target=i386-unknown-none", "--bin=bootstrap"]

[tasks.fulldoc]
description = "Document the bootstrap"
dependencies = ["bootstrap"]
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot"}
command = "cargo"
args = ["rustdoc", "--target=i386-unknown-none", "--bin=bootstrap", "--", "--document-private-items"]
