#!/bin/sh

usage()
{
    cat << EOF
Usage: ./update_subtree <remote> <branch> <prefix>
Where:
    remote: The name of the remote to use.
    branch: The target branch on the remote to use.
    prefix: the path to the directory to update
EOF
    exit 1
}

if [ $# -lt 3 ]; then
    usage
fi

remote=$1
branch=$2
prefix=$3

git fetch "$remote" &&
git rm -r --ignore-unmatch "$prefix" &&
git read-tree --prefix="$prefix" "${remote}/${branch}" &&
git checkout -- "$prefix" &&
git commit -m "update $prefix from $remote $branch"