[dependencies.core]
stage = 0

[dependencies.alloc]
stage = 0
features = ['compiler-builtins-mem']

[target.i386-unknown-sunrise-user.dependencies.std]
stage = 1

[patch.crates-io.libc]
git = "https://github.com/sunriseos/libc.git"
branch = "sunrise-2020-05-27"

[patch.crates-io.compiler_builtins]
git = "https://github.com/sunriseos/compiler-builtins.git"
branch = "sunrise-2022-08-19"

[patch."https://github.com/sunriseos/sunriseos.git".sunrise-libuser]
path = "libuser"
