var N = null;var sourcesIndex = {};
sourcesIndex["disk_initializer"] = {"name":"","files":["gpt.rs","main.rs"]};
sourcesIndex["docs"] = {"name":"","files":["main.rs"]};
sourcesIndex["sunrise_ahci"] = {"name":"","files":["disk.rs","fis.rs","hba.rs","main.rs","pci.rs"]};
sourcesIndex["sunrise_bootstrap"] = {"name":"","dirs":[{"name":"gdt","files":["i386.rs","mod.rs","segment_selector.rs"]},{"name":"paging","files":["entry.rs","mod.rs","table.rs"]}],"files":["address.rs","bootstrap_logging.rs","bootstrap_stack.rs","elf_loader.rs","frame_alloc.rs","main.rs"]};
sourcesIndex["sunrise_fs"] = {"name":"","dirs":[{"name":"detail","dirs":[{"name":"driver","dirs":[{"name":"fat","files":["directory.rs","error.rs","file.rs","filesystem.rs","mod.rs"]}],"files":["mod.rs"]},{"name":"gpt","files":["mod.rs"]}],"files":["mod.rs","utils.rs"]},{"name":"interface","files":["driver.rs","filesystem.rs","mod.rs","storage.rs"]},{"name":"ipc","files":["mod.rs"]}],"files":["main.rs"]};
sourcesIndex["sunrise_kernel"] = {"name":"","dirs":[{"name":"devices","files":["hpet.rs","ioapic.rs","lapic.rs","mod.rs","pic.rs","pit.rs","rs232.rs"]},{"name":"frame_allocator","files":["i386.rs","mod.rs","physical_mem_region.rs"]},{"name":"i386","dirs":[{"name":"structures","files":["gdt.rs","idt.rs","mod.rs"]}],"files":["acpi.rs","gdt.rs","interrupt.rs","interrupt_service_routines.rs","mod.rs","multiboot.rs","process_switch.rs","registers.rs","stack.rs"]},{"name":"ipc","files":["mod.rs","port.rs","session.rs"]},{"name":"log_impl","dirs":[{"name":"filter","files":["mod.rs","string.rs"]}],"files":["mod.rs"]},{"name":"paging","dirs":[{"name":"arch","dirs":[{"name":"i386","files":["entry.rs","lands.rs","mod.rs","table.rs"]}],"files":["mod.rs"]}],"files":["bookkeeping.rs","cross_process.rs","hierarchical_table.rs","kernel_memory.rs","lands.rs","mapping.rs","mod.rs","process_memory.rs"]},{"name":"process","files":["capabilities.rs","thread_local_storage.rs"]},{"name":"sync","files":["mod.rs","mutex.rs","spin_lock.rs","spin_lock_irq.rs"]}],"files":["checks.rs","cpu_locals.rs","elf_loader.rs","error.rs","event.rs","heap_allocator.rs","main.rs","mem.rs","panic.rs","process.rs","scheduler.rs","syscalls.rs","timer.rs","utils.rs"]};
sourcesIndex["sunrise_keyboard"] = {"name":"","files":["main.rs","ps2.rs"]};
sourcesIndex["sunrise_libkern"] = {"name":"","files":["error.rs","lib.rs","process.rs"]};
sourcesIndex["sunrise_libtimezone"] = {"name":"","dirs":[{"name":"misc","files":["mod.rs"]}],"files":["conversion.rs","lib.rs","utils.rs"]};
sourcesIndex["sunrise_libuser"] = {"name":"","dirs":[{"name":"ipc","files":["mod.rs","server.rs"]}],"files":["allocator.rs","argv.rs","caps.rs","error.rs","futures.rs","lib.rs","log_impl.rs","mem.rs","ps2.rs","syscalls.rs","terminal.rs","thread_local_storage.rs","threads.rs","types.rs","window.rs","zero_box.rs"]};
sourcesIndex["sunrise_libutils"] = {"name":"","dirs":[{"name":"io","files":["mmio.rs","mod.rs","pio.rs"]}],"files":["cursor.rs","lib.rs","loop_future.rs"]};
sourcesIndex["sunrise_loader"] = {"name":"","files":["elf_loader.rs","main.rs"]};
sourcesIndex["sunrise_shell"] = {"name":"","dirs":[{"name":"subcommands","files":["cd.rs","connect.rs","exit.rs","help.rs","kill.rs","ps.rs","pwd.rs","showgif.rs","test_divide_by_zero.rs","test_page_fault.rs","test_threads.rs","useradd.rs"]}],"files":["main.rs","subcommands.rs"]};
sourcesIndex["sunrise_sm"] = {"name":"","files":["main.rs"]};
sourcesIndex["sunrise_time"] = {"name":"","files":["main.rs","timezone.rs"]};
sourcesIndex["sunrise_vi"] = {"name":"","files":["main.rs","terminal.rs","vbe.rs"]};
sourcesIndex["sunrise_wall_clock"] = {"name":"","files":["main.rs"]};
sourcesIndex["swipc_gen"] = {"name":"","files":["gen_rust_code.rs","itemmod.rs","lib.rs"]};
sourcesIndex["swipc_parser"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
